# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbreprod',
                'doc_host': 'https://nicole-brewer.github.io',
                'git_url': 'https://github.com/nicole-brewer/nbreprod',
                'lib_path': 'nbreprod'},
  'syms': {'nbreprod.core': {'nbreprod.core.foo': ('core.html#foo', 'nbreprod/core.py')}}}